name: yaml-validator
on: push
jobs: 
  validate-yaml: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: schemas/schema.yml
      